{
   "jobs" : {
      "deploy_github_nightly" : {
         "if" : "${{ github.ref == 'refs/heads/nightly' }}",
         "permissions" : {
            "contents" : "write"
         },
         "runs-on" : "ubuntu-latest",
         "steps" : [
            {
               "env" : {
                  "GH_ACCESS_TOKEN" : "${{ secrets.GH_ACCESS_TOKEN }}"
               },
               "run" : "curl -f -s -S --request POST --header \u0022Authorization:token $GH_ACCESS_TOKEN\u0022 --header \u0022Content-Type:application/json\u0022 --data-binary \u0022{\u005C\u0022base\u005C\u0022:\u005C\u0022master\u005C\u0022,\u005C\u0022head\u005C\u0022:\u005C\u0022$GITHUB_SHA\u005C\u0022,\u005C\u0022commit_message\u005C\u0022:\u005C\u0022auto-merge $GITHUB_REF into master\u005C\u0022}\u0022 \u0022https://api.github.com/repos/$GITHUB_REPOSITORY/merges\u0022"
            },
            {
               "env" : {
                  "BWALLER_URL" : "${{ secrets.BWALLER_URL }}"
               },
               "run" : "curl -sSf $BWALLER_URL | BWALL_GROUP=merger.${GITHUB_REF/refs\u005C/heads\u005C//} BWALL_NAME=${GITHUB_REPOSITORY} bash"
            }
         ]
      },
      "deploy_github_staging" : {
         "if" : "${{ github.ref == 'refs/heads/staging' }}",
         "permissions" : {
            "contents" : "write"
         },
         "runs-on" : "ubuntu-latest",
         "steps" : [
            {
               "env" : {
                  "GH_ACCESS_TOKEN" : "${{ secrets.GH_ACCESS_TOKEN }}"
               },
               "run" : "curl -f -s -S --request POST --header \u0022Authorization:token $GH_ACCESS_TOKEN\u0022 --header \u0022Content-Type:application/json\u0022 --data-binary \u0022{\u005C\u0022base\u005C\u0022:\u005C\u0022master\u005C\u0022,\u005C\u0022head\u005C\u0022:\u005C\u0022$GITHUB_SHA\u005C\u0022,\u005C\u0022commit_message\u005C\u0022:\u005C\u0022auto-merge $GITHUB_REF into master\u005C\u0022}\u0022 \u0022https://api.github.com/repos/$GITHUB_REPOSITORY/merges\u0022"
            },
            {
               "env" : {
                  "BWALLER_URL" : "${{ secrets.BWALLER_URL }}"
               },
               "run" : "curl -sSf $BWALLER_URL | BWALL_GROUP=merger.${GITHUB_REF/refs\u005C/heads\u005C//} BWALL_NAME=${GITHUB_REPOSITORY} bash"
            }
         ]
      }
   },
   "name" : "test",
   "on" : {
      "push" : {
      }
   }
}
